config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :attendances
  resources :marks
  resources :real_classes
  resources :class_templates
  resources :subjects
  resources :parents
  resources :teachers
  resources :students
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable
  belongs_to :teacher, optional: true
  belongs_to :student, optional: true
  belongs_to :parent, optional: true

  after_create :send_email

  def send_email
    RestClient.get 'http://sebastian_w_lin_mailer_web_1:3001/submit_email'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :real_class
  belongs_to :student

  def display_name
     presence
  end
end

app/models/class_template.rb
class ClassTemplate < ApplicationRecord
  has_many :class_templates
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :real_class
  belongs_to :teacher
  belongs_to :student
  belongs_to :subject

  def display_name
     mark
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :real_class
  belongs_to :teacher
  belongs_to :student

  def display_name
     note
  end
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_many :admin_user
  has_many :students

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/models/real_class.rb
class RealClass < ApplicationRecord
  has_many :marks
  has_many :notes
  has_many :attendances
  has_and_belongs_to_many :students
  has_and_belongs_to_many :subjects
  belongs_to :class_template
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :marks
  has_many :attendances
  has_many :notes
  has_and_belongs_to_many :real_classes
  has_many :parents
  has_many :admin_user

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :marks
  has_many :teachers
  has_many :class_templates
  has_and_belongs_to_many :real_classes
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :marks
  has_many :notes
  has_many :real_classes
  has_many :subjects
  has_many :admin_user

  after_create :send_email

  def send_email
    RestClient.get 'http://sebastian_w_lin_mailer_web_1:3001/submit_email'
  end

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/controllers/marks_controller.rb
class MarksController < InheritedResources::Base

  private

    def mark_params
      params.require(:mark).permit(:mark, :description)
    end

end

app/controllers/notes_controller.rb
class NotesController < InheritedResources::Base

  private

    def note_params
      params.require(:note).permit(:note, :valid)
    end

end

app/controllers/parents_controller.rb
class ParentsController < InheritedResources::Base

  private

    def parent_params
      params.require(:parent).permit(:first_name, :last_name, :city, :address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/real_classes_helper.rb
module RealClassesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/marks/_form.html.erb
<%= form_with(model: mark, local: true) do |form| %>
  <% if mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mark %>
    <%= form.text_field :mark %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marks</h1>

<table>
  <thead>
    <tr>
      <th>Mark</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each do |mark| %>
      <tr>
        <td><%= mark.mark %></td>
        <td><%= mark.description %></td>
        <td><%= link_to 'Show', mark %></td>
        <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
        <td><%= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mark', new_mark_path %>

app/views/marks/new.html.erb
<h1>New Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mark:</strong>
  <%= @mark.mark %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mark.description %>
</p>

<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :valid %>
    <%= form.check_box :valid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Valid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.note %></td>
        <td><%= note.valid %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @note.note %>
</p>

<p>
  <strong>Valid:</strong>
  <%= @note.valid %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/parents/_form.html.erb
<%= form_with(model: parent, local: true) do |form| %>
  <% if parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parents</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>City</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.first_name %></td>
        <td><%= parent.last_name %></td>
        <td><%= parent.city %></td>
        <td><%= parent.address %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @parent.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @parent.last_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @parent.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @parent.address %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>