config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :attendances
  resources :marks
  resources :real_classes
  resources :class_templates
  resources :subjects
  resources :parents
  resources :teachers
  resources :students
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable
  belongs_to :teacher, optional: true
  belongs_to :student, optional: true
  belongs_to :parent, optional: true

  after_create :send_email

  def send_email
    RestClient.get 'http://sebastian_w_lin_mailer_web_1:3001/submit_email'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :real_class
  belongs_to :student

  def display_name
     presence
  end
end

app/models/class_template.rb
class ClassTemplate < ApplicationRecord
  has_many :class_templates
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :real_class
  belongs_to :teacher
  belongs_to :student
  belongs_to :subject

  def display_name
     mark
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :real_class
  belongs_to :teacher
  belongs_to :student

  def display_name
     note
  end
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_many :admin_user
  has_many :students

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/models/real_class.rb
class RealClass < ApplicationRecord
  has_many :marks
  has_many :notes
  has_many :attendances
  has_and_belongs_to_many :students
  has_and_belongs_to_many :subjects
  belongs_to :class_template
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :marks
  has_many :attendances
  has_many :notes
  has_and_belongs_to_many :real_classes
  has_many :parents
  has_many :admin_user

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :marks
  has_many :teachers
  has_many :class_templates
  has_and_belongs_to_many :real_classes
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :marks
  has_many :notes
  has_many :real_classes
  has_many :subjects
  has_many :admin_user

  after_create :send_email

  def send_email
    RestClient.get 'http://sebastian_w_lin_mailer_web_1:3001/submit_email'
  end

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/controllers/marks_controller.rb
class MarksController < InheritedResources::Base

  private

    def mark_params
      params.require(:mark).permit(:mark, :description)
    end

end

app/controllers/notes_controller.rb
class NotesController < InheritedResources::Base

  private

    def note_params
      params.require(:note).permit(:note, :valid)
    end

end

app/controllers/teachers_controller.rb
class TeachersController < InheritedResources::Base

  private

    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/real_classes_helper.rb
module RealClassesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>