config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :attendances
  resources :marks
  resources :real_classes
  resources :class_templates
  resources :subjects
  resources :parents
  resources :teachers
  resources :students
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable
  belongs_to :teacher, optional: true
  belongs_to :student, optional: true
  belongs_to :parent, optional: true

  after_create :send_email

  def send_email
    RestClient.get 'http://sebastian_w_lin_mailer_web_1:3001/submit_email'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :real_class
  belongs_to :student

  def display_name
     presence
  end
end

app/models/class_template.rb
class ClassTemplate < ApplicationRecord
  has_many :class_templates
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :real_class
  belongs_to :teacher
  belongs_to :student
  belongs_to :subject

  def display_name
     mark
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :real_class
  belongs_to :teacher
  belongs_to :student

  def display_name
     note
  end
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_many :admin_user
  has_many :students

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/models/real_class.rb
class RealClass < ApplicationRecord
  has_many :marks
  has_many :notes
  has_many :attendances
  has_and_belongs_to_many :students
  has_and_belongs_to_many :subjects
  belongs_to :class_template
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :marks
  has_many :attendances
  has_many :notes
  has_and_belongs_to_many :real_classes
  has_many :parents
  has_many :admin_user

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :marks
  has_many :teachers
  has_many :class_templates
  has_and_belongs_to_many :real_classes
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :marks
  has_many :notes
  has_many :real_classes
  has_many :subjects
  has_many :admin_user

  after_create :send_email

  def send_email
    RestClient.get 'http://sebastian_w_lin_mailer_web_1:3001/submit_email'
  end

  def display_name
     "#{first_name} #{last_name}"
  end
end

app/controllers/marks_controller.rb
class MarksController < InheritedResources::Base

  private

    def mark_params
      params.require(:mark).permit(:mark, :description)
    end

end

app/controllers/real_classes_controller.rb
class RealClassesController < InheritedResources::Base

  private

    def real_class_params
      params.require(:real_class).permit(:name, :year, :semester, :active, :start_date, :end_date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/real_classes_helper.rb
module RealClassesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/real_classes/_form.html.erb
<%= form_with(model: real_class, local: true) do |form| %>
  <% if real_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(real_class.errors.count, "error") %> prohibited this real_class from being saved:</h2>

      <ul>
      <% real_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.number_field :semester %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/real_classes/edit.html.erb
<h1>Editing Real Class</h1>

<%= render 'form', real_class: @real_class %>

<%= link_to 'Show', @real_class %> |
<%= link_to 'Back', real_classes_path %>

app/views/real_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Real Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Semester</th>
      <th>Active</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @real_classes.each do |real_class| %>
      <tr>
        <td><%= real_class.name %></td>
        <td><%= real_class.year %></td>
        <td><%= real_class.semester %></td>
        <td><%= real_class.active %></td>
        <td><%= real_class.start_date %></td>
        <td><%= real_class.end_date %></td>
        <td><%= link_to 'Show', real_class %></td>
        <td><%= link_to 'Edit', edit_real_class_path(real_class) %></td>
        <td><%= link_to 'Destroy', real_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Real Class', new_real_class_path %>

app/views/real_classes/new.html.erb
<h1>New Real Class</h1>

<%= render 'form', real_class: @real_class %>

<%= link_to 'Back', real_classes_path %>

app/views/real_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @real_class.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @real_class.year %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @real_class.semester %>
</p>

<p>
  <strong>Active:</strong>
  <%= @real_class.active %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @real_class.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @real_class.end_date %>
</p>

<%= link_to 'Edit', edit_real_class_path(@real_class) %> |
<%= link_to 'Back', real_classes_path %>